<#
.SYNOPSIS
    {Brief description of what the script configures}

.DESCRIPTION
    {Detailed description including which Entra Suite features are configured.}
    Generated by entra-poc-advisor on {date}. Scenario: {scenario-name}

.PARAMETER TenantId
    The tenant ID to connect to. If omitted, uses the current context.

.PARAMETER PilotGroupName
    Name of the security group containing pilot users. Default: "POC-Pilot-Users"

.PARAMETER WhatIf
    Shows what would be configured without making changes.

.EXAMPLE
    .\{script-name}.ps1 -WhatIf
    Preview all changes without applying them.

.NOTES
    Idempotent -- safe to run multiple times. Will NOT delete existing configuration.
    Required modules: Microsoft.Graph
    Required permissions: {required-graph-scopes}
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory = $false)]
    [string]$TenantId,

    [Parameter(Mandatory = $false)]
    [string]$PilotGroupName = "POC-Pilot-Users"
)

# ============================================================================
# Prerequisites Check
# ============================================================================
#region Prerequisites
Write-Host "Checking prerequisites..." -ForegroundColor Cyan
if (-not (Get-Module -ListAvailable -Name "Microsoft.Graph")) {
    Write-Host "ERROR: Microsoft.Graph module not found. Install with:" -ForegroundColor Red
    Write-Host "  Install-Module Microsoft.Graph -Scope CurrentUser" -ForegroundColor Yellow
    exit 1
}
Import-Module Microsoft.Graph
#endregion

# ============================================================================
# Authentication
# ============================================================================
#region Authentication
Write-Host "Connecting to Microsoft Graph..." -ForegroundColor Cyan
$connectParams = @{ Scopes = @({required-graph-scopes}) }
if ($TenantId) { $connectParams.TenantId = $TenantId }
Connect-MgGraph @connectParams
$context = Get-MgContext
if (-not $context) {
    Write-Host "ERROR: Failed to connect to Microsoft Graph." -ForegroundColor Red
    exit 1
}
Write-Host "  Connected to tenant: $($context.TenantId)" -ForegroundColor Green
#endregion

# ============================================================================
# Step 1: {step-1-title}
# ============================================================================
#region Step1
Write-Host "`n[1/{total-steps}] {step-1-description}..." -ForegroundColor Cyan
try {
    $existing = $null
    try { $existing = Invoke-MgGraphRequest -Method GET -Uri "{step-1-get-endpoint}" -ErrorAction Stop } catch { }
    if ($null -eq $existing) {
        if ($PSCmdlet.ShouldProcess("{step-1-resource-description}", "Create")) {
            $body = @{ <# {step-1-request-body} #> } | ConvertTo-Json -Depth 10
            $result = Invoke-MgGraphRequest -Method POST -Uri "{step-1-post-endpoint}" `
                -Body $body -ContentType "application/json"
            Write-Host "  Created {step-1-resource}: $($result.id)" -ForegroundColor Green
        }
    } else {
        Write-Host "  {step-1-resource} already exists (id: $($existing.id)), skipping." -ForegroundColor Yellow
    }
} catch {
    Write-Host "  ERROR: Failed to configure {step-1-resource}: $_" -ForegroundColor Red
}
#endregion

# ============================================================================
# Summary
# ============================================================================
#region Summary
Write-Host "`n========================================" -ForegroundColor Green
Write-Host "POC Configuration Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host "Scenario: {scenario-name} | Pilot group: $PilotGroupName"
Write-Host "`nNext steps:"
Write-Host "  1. Verify configuration in the Entra admin center"
Write-Host "  2. Test with a pilot user from the $PilotGroupName group"
#endregion
