<#
.SYNOPSIS
    Deploys the "Streamline Employee and Guest Onboarding" POC for Microsoft Entra Suite.

.DESCRIPTION
    Configures Microsoft Entra ID Governance (catalogs, access packages, lifecycle workflows),
    B2B connected organizations, and Conditional Access risk-based policies for a proof-of-concept
    that streamlines onboarding for internal employees and external guests.

    This script does NOT configure Verified ID (Quick Setup is portal-only).

    Generated by entra-poc-assistant on 2026-03-17.
    Scenario: Streamline Employee and Guest Onboarding

.PARAMETER TenantId
    The tenant ID to connect to. If omitted, uses the current context.

.PARAMETER PilotGroupName
    Name of the security group for pilot users. Default: "POC-Onboarding-Pilot"

.PARAMETER PilotGroupDescription
    Description for the pilot group. Default: "Pilot group for employee and guest onboarding POC"

.PARAMETER Department
    Department value used for lifecycle workflow scoping. Default: "Finance"

.PARAMETER CatalogName
    Name of the entitlement management catalog. Default: "Onboarding Resources"

.PARAMETER InternalAccessPackageName
    Name of the access package for internal employees. Default: "Finance Apps for Remote Employees"

.PARAMETER GuestAccessPackageName
    Name of the access package for B2B guests. Default: "Finance Apps for Guest Users"

.PARAMETER ConnectedOrgDomain
    Domain of the external partner organization for B2B. Example: "fabrikam.com"

.PARAMETER BreakGlassGroupName
    Name of the break-glass exclusion group for CA policies. Default: "CA-Exclusion-BreakGlass"

.PARAMETER TestUserObjectIds
    Array of user object IDs to add to the pilot group. Optional.

.PARAMETER InternalTestUserObjectId
    Object ID of the internal test user for lifecycle workflow attribute setup. Optional.

.PARAMETER ResourceGroupIds
    Array of security group IDs to add to the catalog as resources. Optional.

.PARAMETER ResourceAppIds
    Array of enterprise application (service principal) IDs to add to the catalog as resources. Optional.

.PARAMETER WhatIf
    Shows what would be configured without making changes.

.EXAMPLE
    .\Deploy-EmployeeGuestOnboarding.ps1 -WhatIf
    Preview all configuration changes without applying them.

.EXAMPLE
    .\Deploy-EmployeeGuestOnboarding.ps1 -TenantId "contoso.onmicrosoft.com" -ConnectedOrgDomain "fabrikam.com"
    Apply configuration to the specified tenant with a partner organization.

.EXAMPLE
    .\Deploy-EmployeeGuestOnboarding.ps1 -InternalTestUserObjectId "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    Apply configuration and set up test user attributes for lifecycle workflows.

.NOTES
    This script is idempotent and safe to run multiple times.
    It will NOT delete any existing configuration.

    Required modules: Microsoft.Graph
    Required permissions:
        Group.ReadWrite.All
        User.ReadWrite.All
        EntitlementManagement.ReadWrite.All
        Policy.ReadWrite.ConditionalAccess
        Policy.Read.All
        IdentityRiskyUser.Read.All
        CrossTenantInformation.ReadBasic.All

    Run with -WhatIf first to preview changes.
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory = $false)]
    [string]$TenantId,

    [Parameter(Mandatory = $false)]
    [string]$PilotGroupName = "POC-Onboarding-Pilot",

    [Parameter(Mandatory = $false)]
    [string]$PilotGroupDescription = "Pilot group for employee and guest onboarding POC",

    [Parameter(Mandatory = $false)]
    [string]$Department = "Finance",

    [Parameter(Mandatory = $false)]
    [string]$CatalogName = "Onboarding Resources",

    [Parameter(Mandatory = $false)]
    [string]$InternalAccessPackageName = "Finance Apps for Remote Employees",

    [Parameter(Mandatory = $false)]
    [string]$GuestAccessPackageName = "Finance Apps for Guest Users",

    [Parameter(Mandatory = $false)]
    [string]$ConnectedOrgDomain,

    [Parameter(Mandatory = $false)]
    [string]$BreakGlassGroupName = "CA-Exclusion-BreakGlass",

    [Parameter(Mandatory = $false)]
    [string[]]$TestUserObjectIds,

    [Parameter(Mandatory = $false)]
    [string]$InternalTestUserObjectId,

    [Parameter(Mandatory = $false)]
    [string[]]$ResourceGroupIds,

    [Parameter(Mandatory = $false)]
    [string[]]$ResourceAppIds
)

$ErrorActionPreference = "Continue"
$totalSteps = 10
$currentStep = 0

# ============================================================================
# Prerequisites Check
# ============================================================================
#region Prerequisites
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "Entra POC: Streamline Employee & Guest Onboarding" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan
Write-Host "Checking prerequisites..." -ForegroundColor Cyan

if (-not (Get-Module -ListAvailable -Name "Microsoft.Graph")) {
    Write-Host "  ERROR: Microsoft.Graph module not found. Install with:" -ForegroundColor Red
    Write-Host "    Install-Module Microsoft.Graph -Scope CurrentUser" -ForegroundColor Yellow
    exit 1
}
Write-Host "  Microsoft.Graph module found." -ForegroundColor Green

Import-Module Microsoft.Graph.Authentication -ErrorAction Stop
#endregion

# ============================================================================
# Authentication
# ============================================================================
#region Authentication
Write-Host "`nConnecting to Microsoft Graph..." -ForegroundColor Cyan

$scopes = @(
    "Group.ReadWrite.All",
    "User.ReadWrite.All",
    "EntitlementManagement.ReadWrite.All",
    "Policy.ReadWrite.ConditionalAccess",
    "Policy.Read.All",
    "IdentityRiskyUser.Read.All"
)

$connectParams = @{
    Scopes = $scopes
}
if ($TenantId) {
    $connectParams.TenantId = $TenantId
}

Connect-MgGraph @connectParams

$context = Get-MgContext
if (-not $context) {
    Write-Host "  ERROR: Failed to connect to Microsoft Graph." -ForegroundColor Red
    exit 1
}
Write-Host "  Connected to tenant: $($context.TenantId)" -ForegroundColor Green

# Validate licenses
Write-Host "`nValidating licenses..." -ForegroundColor Cyan
try {
    $skus = Invoke-MgGraphRequest -Method GET -Uri "https://graph.microsoft.com/v1.0/subscribedSkus" -ErrorAction Stop
    $relevantSkus = @(
        "Microsoft Entra Suite",
        "ENTRA_SUITE",
        "AAD_PREMIUM_P2",
        "IDENTITY_GOVERNANCE",
        "VERIFIED_ID"
    )
    $foundLicenses = @()
    foreach ($sku in $skus.value) {
        foreach ($plan in $sku.servicePlans) {
            if ($relevantSkus -contains $plan.servicePlanName) {
                $foundLicenses += $plan.servicePlanName
            }
        }
    }
    if ($foundLicenses.Count -gt 0) {
        Write-Host "  Found relevant license plans: $($foundLicenses -join ', ')" -ForegroundColor Green
    } else {
        Write-Host "  WARNING: No Entra Suite or ID Governance license plans detected. Verify licenses manually." -ForegroundColor Yellow
    }
} catch {
    Write-Host "  WARNING: Could not validate licenses: $_" -ForegroundColor Yellow
    Write-Host "  Continuing -- verify licenses manually in the Entra admin center." -ForegroundColor Yellow
}
#endregion

# ============================================================================
# Step 1: Create Pilot Security Group
# ============================================================================
#region Step1
$currentStep++
Write-Host "`n[$currentStep/$totalSteps] Creating pilot security group '$PilotGroupName'..." -ForegroundColor Cyan

$pilotGroupId = $null
try {
    $existingGroups = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/groups?`$filter=displayName eq '$PilotGroupName'&`$select=id,displayName" `
        -ErrorAction Stop

    if ($existingGroups.value.Count -gt 0) {
        $pilotGroupId = $existingGroups.value[0].id
        Write-Host "  Pilot group already exists (id: $pilotGroupId), skipping creation." -ForegroundColor Yellow
    } else {
        if ($PSCmdlet.ShouldProcess($PilotGroupName, "Create security group")) {
            $groupBody = @{
                displayName     = $PilotGroupName
                description     = $PilotGroupDescription
                securityEnabled = $true
                mailEnabled     = $false
                mailNickname    = ($PilotGroupName -replace '[^a-zA-Z0-9]', '').ToLower()
                groupTypes      = @()
            } | ConvertTo-Json -Depth 5

            $newGroup = Invoke-MgGraphRequest -Method POST `
                -Uri "https://graph.microsoft.com/v1.0/groups" `
                -Body $groupBody -ContentType "application/json"
            $pilotGroupId = $newGroup.id
            Write-Host "  Created pilot group: $($newGroup.displayName) (id: $pilotGroupId)" -ForegroundColor Green
        }
    }

    # Add test users to the pilot group
    if ($TestUserObjectIds -and $pilotGroupId) {
        foreach ($userId in $TestUserObjectIds) {
            try {
                $members = Invoke-MgGraphRequest -Method GET `
                    -Uri "https://graph.microsoft.com/v1.0/groups/$pilotGroupId/members?`$select=id" `
                    -ErrorAction Stop
                $isMember = $members.value | Where-Object { $_.id -eq $userId }

                if (-not $isMember) {
                    if ($PSCmdlet.ShouldProcess("User $userId", "Add to group $PilotGroupName")) {
                        $memberBody = @{
                            "@odata.id" = "https://graph.microsoft.com/v1.0/directoryObjects/$userId"
                        } | ConvertTo-Json
                        Invoke-MgGraphRequest -Method POST `
                            -Uri "https://graph.microsoft.com/v1.0/groups/$pilotGroupId/members/`$ref" `
                            -Body $memberBody -ContentType "application/json"
                        Write-Host "  Added user $userId to pilot group." -ForegroundColor Green
                    }
                } else {
                    Write-Host "  User $userId is already a member, skipping." -ForegroundColor Yellow
                }
            } catch {
                Write-Host "  WARNING: Could not add user $userId to group: $_" -ForegroundColor Yellow
            }
        }
    }
} catch {
    Write-Host "  ERROR: Failed to create pilot group: $_" -ForegroundColor Red
}
#endregion

# ============================================================================
# Step 2: Create Break-Glass Exclusion Group
# ============================================================================
#region Step2
$currentStep++
Write-Host "`n[$currentStep/$totalSteps] Creating break-glass exclusion group '$BreakGlassGroupName'..." -ForegroundColor Cyan

$breakGlassGroupId = $null
try {
    $existingBG = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/groups?`$filter=displayName eq '$BreakGlassGroupName'&`$select=id,displayName" `
        -ErrorAction Stop

    if ($existingBG.value.Count -gt 0) {
        $breakGlassGroupId = $existingBG.value[0].id
        Write-Host "  Break-glass group already exists (id: $breakGlassGroupId), skipping creation." -ForegroundColor Yellow
    } else {
        if ($PSCmdlet.ShouldProcess($BreakGlassGroupName, "Create security group")) {
            $bgBody = @{
                displayName     = $BreakGlassGroupName
                description     = "Emergency access accounts excluded from all Conditional Access policies"
                securityEnabled = $true
                mailEnabled     = $false
                mailNickname    = "caexclusionbg"
                groupTypes      = @()
            } | ConvertTo-Json -Depth 5

            $newBG = Invoke-MgGraphRequest -Method POST `
                -Uri "https://graph.microsoft.com/v1.0/groups" `
                -Body $bgBody -ContentType "application/json"
            $breakGlassGroupId = $newBG.id
            Write-Host "  Created break-glass group: $($newBG.displayName) (id: $breakGlassGroupId)" -ForegroundColor Green
        }
    }
} catch {
    Write-Host "  ERROR: Failed to create break-glass group: $_" -ForegroundColor Red
}
#endregion

# ============================================================================
# Step 3: Configure Test User Attributes
# ============================================================================
#region Step3
$currentStep++
Write-Host "`n[$currentStep/$totalSteps] Configuring test user attributes for lifecycle workflows..." -ForegroundColor Cyan

if ($InternalTestUserObjectId) {
    try {
        $tomorrow = (Get-Date).AddDays(1).ToString("yyyy-MM-ddT00:00:00Z")
        if ($PSCmdlet.ShouldProcess("User $InternalTestUserObjectId", "Set department=$Department, employeeHireDate=$tomorrow")) {
            $userBody = @{
                department       = $Department
                employeeHireDate = $tomorrow
                employeeType     = "Employee"
            } | ConvertTo-Json -Depth 5

            Invoke-MgGraphRequest -Method PATCH `
                -Uri "https://graph.microsoft.com/v1.0/users/$InternalTestUserObjectId" `
                -Body $userBody -ContentType "application/json"
            Write-Host "  Updated user attributes: department=$Department, employeeHireDate=$tomorrow" -ForegroundColor Green
        }
    } catch {
        Write-Host "  ERROR: Failed to update user attributes: $_" -ForegroundColor Red
    }
} else {
    Write-Host "  No -InternalTestUserObjectId provided. Skipping attribute setup." -ForegroundColor Yellow
    Write-Host "  TIP: Set department and employeeHireDate manually or re-run with -InternalTestUserObjectId." -ForegroundColor Yellow
}
#endregion

# ============================================================================
# Step 4: Add Connected Organization (B2B)
# ============================================================================
#region Step4
$currentStep++
Write-Host "`n[$currentStep/$totalSteps] Configuring B2B connected organization..." -ForegroundColor Cyan

$connectedOrgId = $null
if ($ConnectedOrgDomain) {
    try {
        $existingOrgs = Invoke-MgGraphRequest -Method GET `
            -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/connectedOrganizations?`$filter=displayName eq '$ConnectedOrgDomain'" `
            -ErrorAction Stop

        if ($existingOrgs.value.Count -gt 0) {
            $connectedOrgId = $existingOrgs.value[0].id
            Write-Host "  Connected organization '$ConnectedOrgDomain' already exists (id: $connectedOrgId), skipping." -ForegroundColor Yellow
        } else {
            if ($PSCmdlet.ShouldProcess($ConnectedOrgDomain, "Create connected organization")) {
                $connOrgBody = @{
                    displayName    = $ConnectedOrgDomain
                    description    = "Partner organization for onboarding POC"
                    identitySources = @(
                        @{
                            "@odata.type" = "#microsoft.graph.domainIdentitySource"
                            domainName    = $ConnectedOrgDomain
                            displayName   = $ConnectedOrgDomain
                        }
                    )
                    state          = "configured"
                } | ConvertTo-Json -Depth 10

                $newOrg = Invoke-MgGraphRequest -Method POST `
                    -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/connectedOrganizations" `
                    -Body $connOrgBody -ContentType "application/json"
                $connectedOrgId = $newOrg.id
                Write-Host "  Created connected organization: $ConnectedOrgDomain (id: $connectedOrgId)" -ForegroundColor Green
            }
        }
    } catch {
        Write-Host "  ERROR: Failed to configure connected organization: $_" -ForegroundColor Red
    }
} else {
    Write-Host "  No -ConnectedOrgDomain provided. Skipping B2B connected organization setup." -ForegroundColor Yellow
    Write-Host "  TIP: Re-run with -ConnectedOrgDomain 'partner.com' to configure B2B." -ForegroundColor Yellow
}
#endregion

# ============================================================================
# Step 5: Create Access Catalog
# ============================================================================
#region Step5
$currentStep++
Write-Host "`n[$currentStep/$totalSteps] Creating entitlement management catalog '$CatalogName'..." -ForegroundColor Cyan

$catalogId = $null
try {
    $existingCatalogs = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/catalogs?`$filter=displayName eq '$CatalogName'" `
        -ErrorAction Stop

    if ($existingCatalogs.value.Count -gt 0) {
        $catalogId = $existingCatalogs.value[0].id
        Write-Host "  Catalog '$CatalogName' already exists (id: $catalogId), skipping creation." -ForegroundColor Yellow
    } else {
        if ($PSCmdlet.ShouldProcess($CatalogName, "Create entitlement management catalog")) {
            $catalogBody = @{
                displayName         = $CatalogName
                description         = "Resources for employee and guest onboarding POC"
                isExternallyVisible = $true
            } | ConvertTo-Json -Depth 5

            $newCatalog = Invoke-MgGraphRequest -Method POST `
                -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/catalogs" `
                -Body $catalogBody -ContentType "application/json"
            $catalogId = $newCatalog.id
            Write-Host "  Created catalog: $CatalogName (id: $catalogId)" -ForegroundColor Green
        }
    }

    # Add group resources to catalog
    if ($catalogId -and $ResourceGroupIds) {
        foreach ($groupId in $ResourceGroupIds) {
            try {
                if ($PSCmdlet.ShouldProcess("Group $groupId", "Add to catalog $CatalogName")) {
                    $resourceBody = @{
                        catalogId        = $catalogId
                        requestType      = "adminAdd"
                        accessPackageResource = @{
                            originId     = $groupId
                            originSystem = "AadGroup"
                        }
                    } | ConvertTo-Json -Depth 10

                    Invoke-MgGraphRequest -Method POST `
                        -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/resourceRequests" `
                        -Body $resourceBody -ContentType "application/json"
                    Write-Host "  Added group $groupId to catalog." -ForegroundColor Green
                }
            } catch {
                if ($_.Exception.Message -match "already exists|conflict") {
                    Write-Host "  Group $groupId already in catalog, skipping." -ForegroundColor Yellow
                } else {
                    Write-Host "  WARNING: Could not add group $groupId to catalog: $_" -ForegroundColor Yellow
                }
            }
        }
    }

    # Add application resources to catalog
    if ($catalogId -and $ResourceAppIds) {
        foreach ($appId in $ResourceAppIds) {
            try {
                if ($PSCmdlet.ShouldProcess("Application $appId", "Add to catalog $CatalogName")) {
                    $appResourceBody = @{
                        catalogId        = $catalogId
                        requestType      = "adminAdd"
                        accessPackageResource = @{
                            originId     = $appId
                            originSystem = "AadApplication"
                        }
                    } | ConvertTo-Json -Depth 10

                    Invoke-MgGraphRequest -Method POST `
                        -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/resourceRequests" `
                        -Body $appResourceBody -ContentType "application/json"
                    Write-Host "  Added application $appId to catalog." -ForegroundColor Green
                }
            } catch {
                if ($_.Exception.Message -match "already exists|conflict") {
                    Write-Host "  Application $appId already in catalog, skipping." -ForegroundColor Yellow
                } else {
                    Write-Host "  WARNING: Could not add application $appId to catalog: $_" -ForegroundColor Yellow
                }
            }
        }
    }
} catch {
    Write-Host "  ERROR: Failed to create catalog: $_" -ForegroundColor Red
}
#endregion

# ============================================================================
# Step 6: Create Access Package for Internal Employees
# ============================================================================
#region Step6
$currentStep++
Write-Host "`n[$currentStep/$totalSteps] Creating internal employee access package '$InternalAccessPackageName'..." -ForegroundColor Cyan

$internalPackageId = $null
if ($catalogId) {
    try {
        $existingPkgs = Invoke-MgGraphRequest -Method GET `
            -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackages?`$filter=displayName eq '$InternalAccessPackageName'" `
            -ErrorAction Stop

        if ($existingPkgs.value.Count -gt 0) {
            $internalPackageId = $existingPkgs.value[0].id
            Write-Host "  Access package '$InternalAccessPackageName' already exists (id: $internalPackageId), skipping." -ForegroundColor Yellow
        } else {
            if ($PSCmdlet.ShouldProcess($InternalAccessPackageName, "Create access package")) {
                $pkgBody = @{
                    displayName = $InternalAccessPackageName
                    description = "Provides access to $Department department resources for verified remote employees"
                    catalog     = @{
                        id = $catalogId
                    }
                } | ConvertTo-Json -Depth 10

                $newPkg = Invoke-MgGraphRequest -Method POST `
                    -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackages" `
                    -Body $pkgBody -ContentType "application/json"
                $internalPackageId = $newPkg.id
                Write-Host "  Created access package: $InternalAccessPackageName (id: $internalPackageId)" -ForegroundColor Green
            }
        }

        # Create assignment policy for internal users
        if ($internalPackageId -and $pilotGroupId) {
            try {
                $existingPolicies = Invoke-MgGraphRequest -Method GET `
                    -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/assignmentPolicies?`$filter=accessPackage/id eq '$internalPackageId'" `
                    -ErrorAction Stop

                if ($existingPolicies.value.Count -gt 0) {
                    Write-Host "  Assignment policy already exists for this package, skipping." -ForegroundColor Yellow
                } else {
                    if ($PSCmdlet.ShouldProcess("$InternalAccessPackageName - Policy", "Create assignment policy")) {
                        $policyBody = @{
                            displayName      = "Policy for internal employees"
                            description      = "Allows pilot group members to request access with Verified ID"
                            accessPackageId  = $internalPackageId
                            allowedTargetScope = "specificDirectoryUsers"
                            specificAllowedTargets = @(
                                @{
                                    "@odata.type" = "#microsoft.graph.groupMembers"
                                    groupId       = $pilotGroupId
                                    description   = $PilotGroupName
                                }
                            )
                            expiration = @{
                                type     = "afterDuration"
                                duration = "P90D"
                            }
                            requestorSettings = @{
                                enableTargetsToSelfAddAccess    = $true
                                enableTargetsToSelfUpdateAccess = $true
                                enableTargetsToSelfRemoveAccess = $true
                            }
                            requestApprovalSettings = @{
                                isApprovalRequiredForAdd    = $false
                                isApprovalRequiredForUpdate = $false
                            }
                            reviewSettings = @{
                                isEnabled                       = $true
                                recurrenceType                  = "quarterly"
                                reviewerType                    = "Self"
                                startDateTime                   = (Get-Date).ToString("yyyy-MM-ddT00:00:00Z")
                                durationInDays                  = 25
                                isAccessRecommendationEnabled   = $true
                                isApprovalJustificationRequired = $true
                            }
                        } | ConvertTo-Json -Depth 10

                        $newPolicy = Invoke-MgGraphRequest -Method POST `
                            -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/assignmentPolicies" `
                            -Body $policyBody -ContentType "application/json"
                        Write-Host "  Created assignment policy: $($newPolicy.displayName) (id: $($newPolicy.id))" -ForegroundColor Green
                    }
                }
            } catch {
                Write-Host "  WARNING: Could not create assignment policy: $_" -ForegroundColor Yellow
            }
        }
    } catch {
        Write-Host "  ERROR: Failed to create internal access package: $_" -ForegroundColor Red
    }
} else {
    Write-Host "  SKIPPED: No catalog ID available. Create the catalog first." -ForegroundColor Yellow
}
#endregion

# ============================================================================
# Step 7: Create Access Package for B2B Guests
# ============================================================================
#region Step7
$currentStep++
Write-Host "`n[$currentStep/$totalSteps] Creating guest access package '$GuestAccessPackageName'..." -ForegroundColor Cyan

$guestPackageId = $null
if ($catalogId) {
    try {
        $existingGuestPkgs = Invoke-MgGraphRequest -Method GET `
            -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackages?`$filter=displayName eq '$GuestAccessPackageName'" `
            -ErrorAction Stop

        if ($existingGuestPkgs.value.Count -gt 0) {
            $guestPackageId = $existingGuestPkgs.value[0].id
            Write-Host "  Access package '$GuestAccessPackageName' already exists (id: $guestPackageId), skipping." -ForegroundColor Yellow
        } else {
            if ($PSCmdlet.ShouldProcess($GuestAccessPackageName, "Create access package")) {
                $guestPkgBody = @{
                    displayName = $GuestAccessPackageName
                    description = "Provides access to $Department resources for verified external partners"
                    catalog     = @{
                        id = $catalogId
                    }
                } | ConvertTo-Json -Depth 10

                $newGuestPkg = Invoke-MgGraphRequest -Method POST `
                    -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackages" `
                    -Body $guestPkgBody -ContentType "application/json"
                $guestPackageId = $newGuestPkg.id
                Write-Host "  Created access package: $GuestAccessPackageName (id: $guestPackageId)" -ForegroundColor Green
            }
        }

        # Create assignment policy for external users
        if ($guestPackageId -and $connectedOrgId) {
            try {
                $existingGuestPolicies = Invoke-MgGraphRequest -Method GET `
                    -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/assignmentPolicies?`$filter=accessPackage/id eq '$guestPackageId'" `
                    -ErrorAction Stop

                if ($existingGuestPolicies.value.Count -gt 0) {
                    Write-Host "  Assignment policy already exists for guest package, skipping." -ForegroundColor Yellow
                } else {
                    if ($PSCmdlet.ShouldProcess("$GuestAccessPackageName - Policy", "Create assignment policy")) {
                        $guestPolicyBody = @{
                            displayName      = "Policy for external guests"
                            description      = "Allows connected organization users to request access with Verified ID"
                            accessPackageId  = $guestPackageId
                            allowedTargetScope = "specificConnectedOrganizationUsers"
                            specificAllowedTargets = @(
                                @{
                                    "@odata.type"          = "#microsoft.graph.connectedOrganizationMembers"
                                    connectedOrganizationId = $connectedOrgId
                                    description             = $ConnectedOrgDomain
                                }
                            )
                            expiration = @{
                                type     = "afterDuration"
                                duration = "P30D"
                            }
                            requestorSettings = @{
                                enableTargetsToSelfAddAccess    = $true
                                enableTargetsToSelfUpdateAccess = $true
                                enableTargetsToSelfRemoveAccess = $true
                            }
                            requestApprovalSettings = @{
                                isApprovalRequiredForAdd    = $true
                                isApprovalRequiredForUpdate = $false
                                stages = @(
                                    @{
                                        durationBeforeAutomaticDenial = "P7D"
                                        isApproverJustificationRequired = $true
                                        isEscalationEnabled = $false
                                        primaryApprovers = @()
                                    }
                                )
                            }
                            reviewSettings = @{
                                isEnabled                       = $true
                                recurrenceType                  = "quarterly"
                                reviewerType                    = "Self"
                                startDateTime                   = (Get-Date).ToString("yyyy-MM-ddT00:00:00Z")
                                durationInDays                  = 25
                                isAccessRecommendationEnabled   = $true
                                isApprovalJustificationRequired = $true
                            }
                        } | ConvertTo-Json -Depth 10

                        $newGuestPolicy = Invoke-MgGraphRequest -Method POST `
                            -Uri "https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/assignmentPolicies" `
                            -Body $guestPolicyBody -ContentType "application/json"
                        Write-Host "  Created guest assignment policy: $($newGuestPolicy.displayName) (id: $($newGuestPolicy.id))" -ForegroundColor Green
                    }
                }
            } catch {
                Write-Host "  WARNING: Could not create guest assignment policy: $_" -ForegroundColor Yellow
            }
        } elseif (-not $connectedOrgId) {
            Write-Host "  NOTE: No connected organization configured. Guest assignment policy requires -ConnectedOrgDomain." -ForegroundColor Yellow
        }
    } catch {
        Write-Host "  ERROR: Failed to create guest access package: $_" -ForegroundColor Red
    }
} else {
    Write-Host "  SKIPPED: No catalog ID available. Create the catalog first." -ForegroundColor Yellow
}
#endregion

# ============================================================================
# Step 8: Create Joiner Lifecycle Workflow
# ============================================================================
#region Step8
$currentStep++
Write-Host "`n[$currentStep/$totalSteps] Creating joiner lifecycle workflow..." -ForegroundColor Cyan

$joinerWorkflowName = "Onboard New Hire Employee - $Department"
try {
    $existingWorkflows = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identityGovernance/lifecycleWorkflows/workflows?`$filter=displayName eq '$joinerWorkflowName'" `
        -ErrorAction Stop

    if ($existingWorkflows.value.Count -gt 0) {
        Write-Host "  Joiner workflow '$joinerWorkflowName' already exists (id: $($existingWorkflows.value[0].id)), skipping." -ForegroundColor Yellow
    } else {
        if ($PSCmdlet.ShouldProcess($joinerWorkflowName, "Create lifecycle workflow")) {
            # Build task list
            $tasks = @(
                @{
                    isEnabled           = $true
                    taskDefinitionId    = "6fc52c9d-398b-4305-9763-15f42c1676fc"  # Enable User Account
                    displayName         = "Enable User Account"
                    description         = "Enable the user account on hire date"
                    arguments           = @()
                }
            )

            # Add "Add user to group" task if pilot group exists
            if ($pilotGroupId) {
                $tasks += @{
                    isEnabled           = $true
                    taskDefinitionId    = "22085229-5809-45e8-97fd-270d28d66910"  # Add user to group
                    displayName         = "Add user to $PilotGroupName"
                    description         = "Add user to the onboarding pilot group"
                    arguments           = @(
                        @{
                            name  = "groupID"
                            value = $pilotGroupId
                        }
                    )
                }
            }

            $workflowBody = @{
                displayName      = $joinerWorkflowName
                description      = "Automatically provisions $Department department new hires with access and notifications"
                isEnabled        = $true
                isSchedulingEnabled = $true
                category         = "joiner"
                executionConditions = @{
                    "@odata.type" = "#microsoft.graph.identityGovernance.triggerAndScopeBasedConditions"
                    scope = @{
                        "@odata.type" = "#microsoft.graph.identityGovernance.ruleBasedSubjectSet"
                        rule          = "(department eq '$Department')"
                    }
                    trigger = @{
                        "@odata.type"  = "#microsoft.graph.identityGovernance.timeBasedAttributeTrigger"
                        timeBasedAttribute = "employeeHireDate"
                        offsetInDays   = 0
                    }
                }
                tasks = $tasks
            } | ConvertTo-Json -Depth 15

            $newWorkflow = Invoke-MgGraphRequest -Method POST `
                -Uri "https://graph.microsoft.com/v1.0/identityGovernance/lifecycleWorkflows/workflows" `
                -Body $workflowBody -ContentType "application/json"
            Write-Host "  Created joiner workflow: $joinerWorkflowName (id: $($newWorkflow.id))" -ForegroundColor Green
        }
    }
} catch {
    Write-Host "  ERROR: Failed to create joiner workflow: $_" -ForegroundColor Red
    Write-Host "  TIP: Verify that you have Lifecycle Workflows Administrator role and ID Governance license." -ForegroundColor Yellow
}
#endregion

# ============================================================================
# Step 9: Create Leaver Lifecycle Workflow (Optional)
# ============================================================================
#region Step9
$currentStep++
Write-Host "`n[$currentStep/$totalSteps] Creating leaver lifecycle workflow (optional)..." -ForegroundColor Cyan

$leaverWorkflowName = "Offboard Employee - $Department"
try {
    $existingLeaverWF = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identityGovernance/lifecycleWorkflows/workflows?`$filter=displayName eq '$leaverWorkflowName'" `
        -ErrorAction Stop

    if ($existingLeaverWF.value.Count -gt 0) {
        Write-Host "  Leaver workflow '$leaverWorkflowName' already exists (id: $($existingLeaverWF.value[0].id)), skipping." -ForegroundColor Yellow
    } else {
        if ($PSCmdlet.ShouldProcess($leaverWorkflowName, "Create lifecycle workflow")) {
            $leaverBody = @{
                displayName      = $leaverWorkflowName
                description      = "Automatically deprovisions $Department department employees on departure"
                isEnabled        = $true
                isSchedulingEnabled = $true
                category         = "leaver"
                executionConditions = @{
                    "@odata.type" = "#microsoft.graph.identityGovernance.triggerAndScopeBasedConditions"
                    scope = @{
                        "@odata.type" = "#microsoft.graph.identityGovernance.ruleBasedSubjectSet"
                        rule          = "(department eq '$Department')"
                    }
                    trigger = @{
                        "@odata.type"  = "#microsoft.graph.identityGovernance.timeBasedAttributeTrigger"
                        timeBasedAttribute = "employeeLeaveDateTime"
                        offsetInDays   = 0
                    }
                }
                tasks = @(
                    @{
                        isEnabled        = $true
                        taskDefinitionId = "1dfdfcc7-52fa-4c2e-bf3a-e3919cc12950"  # Disable User Account
                        displayName      = "Disable User Account"
                        description      = "Disable the user account on leave date"
                        arguments        = @()
                    },
                    @{
                        isEnabled        = $true
                        taskDefinitionId = "b3a31406-2a15-4c9a-b25b-a658fa5f07fc"  # Remove user from all groups
                        displayName      = "Remove user from all groups"
                        description      = "Remove all group memberships"
                        arguments        = @()
                    },
                    @{
                        isEnabled        = $true
                        taskDefinitionId = "81f7b200-2816-4b3b-8c5d-dc556f07b024"  # Remove user from all Teams
                        displayName      = "Remove user from all Teams"
                        description      = "Remove all Teams memberships"
                        arguments        = @()
                    }
                )
            } | ConvertTo-Json -Depth 15

            $newLeaverWF = Invoke-MgGraphRequest -Method POST `
                -Uri "https://graph.microsoft.com/v1.0/identityGovernance/lifecycleWorkflows/workflows" `
                -Body $leaverBody -ContentType "application/json"
            Write-Host "  Created leaver workflow: $leaverWorkflowName (id: $($newLeaverWF.id))" -ForegroundColor Green
        }
    }
} catch {
    Write-Host "  ERROR: Failed to create leaver workflow: $_" -ForegroundColor Red
}
#endregion

# ============================================================================
# Step 10: Create Sign-in Risk Conditional Access Policy
# ============================================================================
#region Step10
$currentStep++
Write-Host "`n[$currentStep/$totalSteps] Creating sign-in risk Conditional Access policy..." -ForegroundColor Cyan

$caPolicyName = "POC-SignInRisk-RequireMFA"
if ($pilotGroupId -and $breakGlassGroupId) {
    try {
        $existingCA = Invoke-MgGraphRequest -Method GET `
            -Uri "https://graph.microsoft.com/v1.0/identity/conditionalAccess/policies?`$filter=displayName eq '$caPolicyName'" `
            -ErrorAction Stop

        if ($existingCA.value.Count -gt 0) {
            Write-Host "  CA policy '$caPolicyName' already exists (id: $($existingCA.value[0].id)), skipping." -ForegroundColor Yellow
        } else {
            if ($PSCmdlet.ShouldProcess($caPolicyName, "Create Conditional Access policy (report-only mode)")) {
                $caBody = @{
                    displayName = $caPolicyName
                    state       = "enabledForReportingButNotEnforced"
                    conditions  = @{
                        users = @{
                            includeGroups = @($pilotGroupId)
                            excludeGroups = @($breakGlassGroupId)
                        }
                        applications = @{
                            includeApplications = @("All")
                        }
                        signInRiskLevels = @("high", "medium")
                    }
                    grantControls = @{
                        operator        = "OR"
                        builtInControls = @("mfa")
                    }
                    sessionControls = @{
                        signInFrequency = @{
                            value     = 1
                            type      = "hours"
                            isEnabled = $true
                            authenticationType = "primaryAndSecondaryAuthentication"
                            frequencyInterval  = "everyTime"
                        }
                    }
                } | ConvertTo-Json -Depth 10

                $newCA = Invoke-MgGraphRequest -Method POST `
                    -Uri "https://graph.microsoft.com/v1.0/identity/conditionalAccess/policies" `
                    -Body $caBody -ContentType "application/json"
                Write-Host "  Created CA policy: $caPolicyName (id: $($newCA.id))" -ForegroundColor Green
                Write-Host "  Policy state: REPORT-ONLY (review sign-in logs before enabling)" -ForegroundColor Yellow
            }
        }
    } catch {
        Write-Host "  ERROR: Failed to create CA policy: $_" -ForegroundColor Red
        Write-Host "  TIP: Verify Conditional Access Administrator role and P2 license." -ForegroundColor Yellow
    }
} else {
    Write-Host "  SKIPPED: Pilot group or break-glass group not available. Create groups first." -ForegroundColor Yellow
}
#endregion

# ============================================================================
# Summary
# ============================================================================
#region Summary
Write-Host "`n========================================" -ForegroundColor Green
Write-Host "POC Configuration Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host "Scenario: Streamline Employee & Guest Onboarding" -ForegroundColor White
Write-Host "Pilot group: $PilotGroupName" -ForegroundColor White
Write-Host "`nConfigured components:" -ForegroundColor White
Write-Host "  - Pilot security group: $PilotGroupName" -ForegroundColor White
Write-Host "  - Break-glass exclusion group: $BreakGlassGroupName" -ForegroundColor White
Write-Host "  - Access catalog: $CatalogName" -ForegroundColor White
Write-Host "  - Internal access package: $InternalAccessPackageName" -ForegroundColor White
Write-Host "  - Guest access package: $GuestAccessPackageName" -ForegroundColor White
Write-Host "  - Joiner lifecycle workflow: $joinerWorkflowName" -ForegroundColor White
Write-Host "  - Leaver lifecycle workflow: $leaverWorkflowName" -ForegroundColor White
Write-Host "  - Conditional Access policy: $caPolicyName (report-only)" -ForegroundColor White

Write-Host "`nManual steps still required:" -ForegroundColor Yellow
Write-Host "  1. Configure Verified ID Quick Setup in the Entra admin center" -ForegroundColor Yellow
Write-Host "     Portal path: Verified ID > Setup > Get started" -ForegroundColor Yellow
Write-Host "  2. Issue a test workplace credential via My Account" -ForegroundColor Yellow
Write-Host "     URL: https://myaccount.microsoft.com > Get my Verified ID" -ForegroundColor Yellow
Write-Host "  3. Add Verified ID requirement to access packages (portal-only)" -ForegroundColor Yellow
Write-Host "     Edit each access package > Requests > Required Verified IDs > Add issuer" -ForegroundColor Yellow
Write-Host "  4. Configure ID Protection risk notifications" -ForegroundColor Yellow
Write-Host "     Portal path: Protection > Identity Protection > Settings" -ForegroundColor Yellow
Write-Host "  5. Add break-glass accounts to the $BreakGlassGroupName group" -ForegroundColor Yellow
Write-Host "  6. Add resource roles to access packages (groups/apps from catalog)" -ForegroundColor Yellow
Write-Host "  7. Review and switch CA policy from report-only to enforced after validation" -ForegroundColor Yellow

Write-Host "`nTesting steps:" -ForegroundColor Cyan
Write-Host "  1. Run joiner workflow on-demand for test user" -ForegroundColor Cyan
Write-Host "  2. Request access package as internal user at https://myaccess.microsoft.com" -ForegroundColor Cyan
Write-Host "  3. Request access package as external guest" -ForegroundColor Cyan
Write-Host "  4. Simulate user risk to validate CA policy" -ForegroundColor Cyan

Write-Host "`nSee poc-guide-streamline-employee-guest-onboarding.md for full documentation." -ForegroundColor White
#endregion
